#!/bin/bash
coverage run -m pytest --cov test_*.py --workers auto
pytest --cov=../synthpops test_*.py --workers auto

echo 'Creating HTML report...'
coverage html

echo 'Running report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"