#!/bin/bash
coverage run --source=../../synthpops --omit=*census* -m pytest test_*.py

echo 'Creating HTML report...'
coverage html

echo 'Running report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"