'''
Plot the contact matrices for the specified file. The file is generated by create_pop.py
'''

import sciris as sc
from examples.plot_age_mixing_matrices import test_plot_generated_contact_matrix

fn = 'testpop4.pop'
layers = ['H', 'W', 'S', 'LTCF']
density_or_frequency = 'density'

pop = sc.loadobj(fn)

for setting_code in layers:
    fig = test_plot_generated_contact_matrix(
        setting_code=setting_code,
        population=pop,
        title_prefix=fn + ': ',
        density_or_frequency=density_or_frequency)